#gninx is unnecessary here
japp:
  restart: always
  build: ./ReadEmail
  working_dir: /app
  volumes:
  - ./emails/eml:/emails/eml
  - ./emails/msg:/emails/msg
  - ./emails/processed:/emails/processed

db:
    environment:
      POSTGRES_DATABASE: naml
      POSTGRES_PASSWORD: naml
      POSTGRES_ROOT_PASSWORD: naml
      POSTGRES_USER: naml
    image: postgres

phppgadmin:
    environment:
      POSTGRES_HOST: db
    image: einfallstoll/phppgadmin
    links:
    - db:db
    ports:
    - 81:80

web:
    restart: always
    build: ./
    working_dir: /app
    volumes:
    - ./emails/eml:/emails/eml
    - ./emails/msg:/emails/msg
    - ./emails/processed:/emails/processed
    links:
    - db:db
    ports:
    - "5000:5000"
    #command: gunicorn app:app -w 4 -b  0.0.0.0:5000 --name app --log-level=debug --log-file=-
